### ISSUE TITLE
Error in library(ezlimma) : there is no package called 'ezlimma'

### ISSUE THREAD

**Issue by aljones15** [jdreyf/zero2bioinfo#1]
Quitting from lines 437-439 (zero2bioinfo.Rmd) 
Error in library(ezlimma) : there is no package called 'ezlimma'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted

just checked and ezlimma is a github install:

https://rdrr.io/github/jdreyf/ezlimma/

instructions:

install.packages("devtools")
library(devtools)
install_github("jdreyf/ezlimma")

can not quite get this one to work yet. will try and fork and fix this today.

p.s. just noticed your note on the install so my bad however see comment below.

**Comment by aljones15** [comment]
and now this:

Error: (converted from warning) package ‘limma’ is not available (for R version 3.5.1)
upgrade or downgrade required?

ok solved this via:

biocLite("limma")

my bioconductor was out of date.

**Comment by aljones15** [comment]
and needed this too: devtools::install_github(repo="jdreyf/ezlimmaplot", build_vignettes = TRUE)

**Comment by aljones15** [comment]
ok so those additional installations solved the issue also a brew install libgit2 and then a manual install of the git2r was required. closing this looks like the file itself has fairly good instructions.

**Comment by jdreyf** [comment]
Thanks for trying it out!

**Comment by jdreyf** [comment]
@aljones15 thanks for trying it out!
